name: projeto
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # Ícones e Utilitários
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.1.2
  

  # Conexão com Servidor e Armazenamento Seguro
  http: ^1.2.1
  flutter_secure_storage: ^9.1.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/